micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    schema-generate: UPDATE
    dialect: org.hibernate.dialect.PostgreSQLDialect
jpa:
  default.properties.hibernate.hbm2ddl.auto: update